Retrieving data from multiple table
isandeepMakwana/SQL pull request #2
Opened 2022-11-10 01:11 UTC by isandeepMakwana

- images added.
- database file added.
- JOINs added.
- README file updated.

2022-11-10 02:11 UTC, darshan4416 commented on NATURAL JOIN.md
> +In 'Natural Join' do not want to specify the situation
In 'Natural Join' we don't need to specify the condition

2022-11-10 02:15 UTC, darshan4416 requested changes

2022-11-10 02:15 UTC, darshan4416 commented on README.md
> +it simplify our Query  but we only 'USING' when the column name is same in both tables
but we only *use* 'USING'

2022-11-10 02:15 UTC, darshan4416 commented on README.md
> +In 'Natural Join' do not want to specify the situation
*do not need to specify the condition*

2022-11-10 02:15 UTC, darshan4416 commented on README.md
> +In 'Natural Join' do not want to specify the situation
typo in similar

2022-11-10 03:16 UTC, isandeepMakwana commented on README.md
> +In 'Natural Join' do not want to specify the situation
updated

2022-11-11 02:16 UTC, darshan4416 approved these changes

2022-11-11 02:18 UTC, merged